### ISSUE TITLE
libpak fails to use cached dependencies when no CPEs are specified.

### ISSUE THREAD

**Issue by andrew-su** [paketo-buildpacks/libpak#167]
After creating a buildpack using `create-package` with `--include-dependencies` then running `pack buildpack package ...`. The resulting buildpack when included fails to use the cached dependencies and try to download the artifacts.

## Expected Behavior
The buildpack continues without trying to download the dependency.

## Current Behavior
The buildpack tries to download the dependency but fails in an offline environment.

## Steps to Reproduce
Create the buildpack with a dependency, ensuring there are no CPES specified.
Prepare the offline buildpack with `create-package` and `--include-dependencies`
Package the buildpack `pack buildpack package ... `
Include the buildpack for a build. `pack build ... -b <thebuildpack> --network none`

## Motivations
Any dependencies without CPES can not be used offline.

## Note
From what we discovered, the CPE list of the `libpak.BuildpackDependency` retrieved from `DependencyResolver` has`CPEs: []string{nil}` while the result from [parsing the cache toml](https://github.com/paketo-buildpacks/libpak/blob/main/dependency_cache.go#L156-L159) `/dependencies/<sha>.toml` returned a `CPEs: []string{}`. Which caused the comparison to fail.

LibPak Version: 1.61.0

**Comment by dmikusa-pivotal** [comment]
I don't think that it's a valid case to not have the CPE and pURL set. You can technically do it, but this information is included in the generated SBOM. My understanding is that if you don't include this, then scanners will not be able to match up the installed dependency with potential vulnerabilities. It'll be like the dependency is invisible to the scanner, which isn't good.

**Comment by andrew-su** [comment]
In our case, the buildpack dependency we are including is a tarball of our application's dependencies. We plan on adding those items to the SBOM which will provide better information than having a CPE for our tarball.

Another scenario could be if the dependency is providing some additional configuration files.

Regardless of the usage, the bug is still valid where an empty list of CPEs should not become `[]string{nil}`

**Comment by andrew-su** [comment]
I'd be happy to hear more about adding the CPE and pURL to our buildpack if you think it makes sense for us to do so. Let's chat about this on Monday :)

**Comment by c0d1ngm0nk3y** [comment]
Would be fixed by #233 - why comparing the metadata in the first place? If the `shasum` is the same, then it is the right dependency, right?

**Comment by dmikusa** [comment]
Resolved by #240.
