### ISSUE TITLE
libpak should provide the slices.Contains utility

### ISSUE THREAD

**Issue by anthonydahanne** [paketo-buildpacks/libpak#238]
## Describe the Enhancement

Some buildpacks try to reproduce this common utility, it'd be better if it was available in libpak in the first place.

## Motivation &  Possible Solution
You can get this functionality from "golang.org/x/exp/slices" and even copy it from https://cs.opensource.google/go/x/exp/+/master:slices/slices.go

**Comment by dmikusa** [comment]
This is now in Go, *finally*, so we should switch buildpacks to use that.

https://pkg.go.dev/slices#Contains
