### ISSUE TITLE
Create some testing utils for working with and asserting against TOML

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/libpak#257]
## Describe the Enhancement

Buildpacks have a lot of TOML. Working with it is kind of a pain, especially when trying to do comparisons in tests.

We should take some time to write some helper code for working with and asserting against TOML.

## Motivation

I think this will simplify our test cases and make them easier to read.

**Comment by loewenstein** [comment]
@dmikusa Why is this labeled `v2`?
