### ISSUE TITLE
Split `create-package` out of libpak

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/libpak#259]
## Describe the Enhancement

We need to split `create-package` out into its own repo and have it take a dependency on libpak, instead of being included with libpak. This will make it more flexible. It should also enable us to have actual releases of `create-package`, so it can be installed w/out requiring a Go SDK. It should also more easily facilitate some documentation on the tool.

## Motivation

See above.

**Comment by showpune** [comment]
What is the relationship of create-package and https://github.com/paketo-buildpacks/jam, they looks has the same functionalities?

**Comment by dmikusa** [comment]
You are correct in that there is overlap between the two tools, and there are primarily just historical reasons for why we have both. There are some minor differences between them so it wouldn't be a drop-in replacement to move from one to the other. Down the road, we'd like to only have one of these tools but we haven't scoped out how much work it would be to switch.

**Comment by braunsonm** [comment]
Just to chime in, if this is done the `create-package` tool should work without an internet connection (ie not try to install libpak at runtime). Right now the `jam` utility will run `go install packit` as part of its build process.

**Comment by dmikusa** [comment]
@braunsonm FYI, I've started this work see https://github.com/paketo-buildpacks/libpak-tools?tab=readme-ov-file#libpak-tools-package-create

Right now, it will function exactly as it does presently. So if you're able to use `create-package` in an offline environment then it will keep working that way. I'm not sure off hand as we only run it on Github actions which is online. If it does not work in an offline env, feel free to open an issue over on the libpak-tools repo and request it. Right now, we're focused on moving existing functionality into that repo, but when we catch up we'll look at adding new features too.

**Comment by braunsonm** [comment]
Thanks @dmikusa I'll give it a try.

We are using the current create-package offline so as long as it maintains that functionality we should be good and I support moving it out and making it easier to actually acquire (without a go install)

**Comment by dmikusa** [comment]
Awesome. Yes, when we hit a release point. I'll start cutting and publishing releases of the tool on Github. For now, `go install` is the way to do it.

**Comment by braunsonm** [comment]
Unfortunately I'm not seeing these tools as a direct replacement. Unless I'm missing something (the docs are wrong) the equivalent command is `libpak-tools package bundle` which fails on the same buildpack that `create-package` works with (references buildpack which is not present).
Additionally it does not support output destination directories like `create-package` does.

I could raise issues on libpak-tools if you want.

**Comment by dmikusa** [comment]
This is done.
