### ISSUE TITLE
Add a Makefile

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/libpak#260]
## Describe the Enhancement

Add a Makefile.

## Possible Solution

Basically, copy what libcnb has.

## Motivation

We should have a Makefile. It's standard in a lot of Go projects. It also makes it easier to run test, lint, and CI.

**Comment by loewenstein** [comment]
Should this be closed on the basis of #301 or are we intending to fix linters? In the latter case, I suppose the title should be adapted.

**Comment by dmikusa** [comment]
I think this was just not closed out when we merged #301. Closing.
