### ISSUE TITLE
Avoid including http query parameters in downloaded (http) artifact's filename

### ISSUE THREAD

**Issue by semmet95** [paketo-buildpacks/libpak#274]
## Describe the Enhancement
This request is in the context of Paketo's apache-tomcat [buildpack](https://github.com/paketo-buildpacks/apache-tomcat/tree/main). 
We are trying to use a presigned S3 url to download tomcat external configurations, setting the url as the value for the environment variable `BP_TOMCAT_EXT_CONF_URI`. Internally the buildpack [calls](https://github.com/paketo-buildpacks/apache-tomcat/blob/00745a96587fb53984e7b478d5a24aaf0bf78335/tomcat/base.go#L275) libpak. DependencyCache's `Artifact` function.
This function sets the name of the downloaded artifact based on the value returned by the `filepath.Base(uri)` function [call](https://github.com/paketo-buildpacks/libpak/blob/20229c947f55ede8e5c95eda98c5f604a3961ebe/dependency_cache.go#L185).
However, if we use an http uri with query parameters this call will try to set the filename with the query parameters included.

In our case, the S3 presigned url we are using has very long query parameter values, and when `libpak` tries to save the downloaded file with these parameters included in the filename, it runs into _**file name too long**_ error.

## Possible Solution
We can parse the uri using net/url's `Parse` function and then get the clean uri without the query parameters using the `Path` property. We can also put checks to ensure this is done only for http/https URIs.

## Motivation
This would add support for presigned S3 urls to the Tomcat buildpack to provide external configurations.

We already have a PR drafted, let us know if we can mark it ready for review.

**Comment by dmikusa** [comment]
This sounds reasonable. I see your PR, when that's ready let us know.

**Comment by semmet95** [comment]
Thanks @dmikusa for checking the PR.
I've marked it as Ready for Review now.
