### ISSUE TITLE
Can't build twice

### ISSUE THREAD

**Issue by mamachanko** [paketo-buildpacks/libpak#61]
## What happened?

I am exploring buildpacks. I wanted to build my image again, but the second build breaks.

```shell
$ curl -G https://start.spring.io/starter.zip\?type=gradle-project -d dependencies=web -d javaVersion=11 -o demo.zip
$ unzip demo.zip -d .
$ pack config default-builder paketobuildpacks/builder:base # according to https://paketo.io/docs/buildpacks/language-family-buildpacks/java/#about-the-examples
$ pack build demo --path $PWD. # this one works as expected
$ pack build demo --path $PWD
# ...
Paketo Maven Buildpack 5.3.0
  unable to create application layer
  failed to generate expected metadata
  unable to determine java version
  error executing 'javac -version':
   Combined Output: :
  unable to start PTY
  exec: "javac": executable file not found in $PATH
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

Forgive me. I have just begun to use buildpacks. I assume that the build is run in complete isolation. The fact that I am using [sdkman](https://sdkman.io/) to install and select the Java version on the host should not get in the way of buildpacks, should it? The first build works as advertised though. 🤔

```
$ pack version
0.19.0+git-360dbae.build-2550
```

**Comment by dmikusa-pivotal** [comment]
FYI, I have cut release 5.9.1 of the Java buildpack which has a fix for this: https://github.com/paketo-buildpacks/java/releases/tag/v5.9.1. It should get picked up by the builders shortly, probably over the next 8-12 hours.

**Comment by dmikusa-pivotal** [comment]
The fix for this has been picked up in the builders. If you're on the latest builder at the time of writing, 0.1.115-base, you should have the fix.
